"""
Shared Domain Enums for FaceSentry
"""

from enum import Enum


class SystemState(str, Enum):
    """Current operational state of FaceSentry."""
    UNINITIALIZED = "UNINITIALIZED"
    IDLE = "IDLE"
    MONITORING_AUTHENTICATED = "MONITORING_AUTHENTICATED"
    MONITORING_ABSENT = "MONITORING_ABSENT"
    MONITORING_UNKNOWN_FACE = "MONITORING_UNKNOWN_FACE"
    MONITORING_SPOOF_ATTEMPT = "MONITORING_SPOOF_ATTEMPT"
    LOCKED = "LOCKED"
    SNOOZED = "SNOOZED"
    ENROLLING = "ENROLLING"
    ERROR = "ERROR"


class EventType(str, Enum):
    """Categorization for security audit log entries."""
    SYSTEM_STARTUP = "SYSTEM_STARTUP"
    SYSTEM_SHUTDOWN = "SYSTEM_SHUTDOWN"
    USER_AUTHENTICATED = "USER_AUTHENTICATED"
    ABSENCE_DETECTED = "ABSENCE_DETECTED"
    UNKNOWN_FACE_DETECTED = "UNKNOWN_FACE_DETECTED"
    SPOOF_DETECTED = "SPOOF_DETECTED"
    LOCK_TRIGGERED = "LOCK_TRIGGERED"
    PIN_VERIFIED = "PIN_VERIFIED"
    PIN_SETUP = "PIN_SETUP"
    PIN_CHANGED = "PIN_CHANGED"
    PIN_VERIFY_STARTED = "PIN_VERIFY_STARTED"
    PIN_AUTHENTICATED = "PIN_AUTHENTICATED"
    PIN_FAILED = "PIN_FAILED"
    PIN_LOCKOUT_STARTED = "PIN_LOCKOUT_STARTED"
    PIN_RECOVERY_STARTED = "PIN_RECOVERY_STARTED"
    PIN_RECOVERY_EXPIRED = "PIN_RECOVERY_EXPIRED"
    BIOMETRIC_REAUTH_REQUIRED = "BIOMETRIC_REAUTH_REQUIRED"
    ENROLLMENT_COMPLETED = "ENROLLMENT_COMPLETED"
    CONFIG_UPDATED = "CONFIG_UPDATED"
    CAMERA_STATUS_CHANGED = "CAMERA_STATUS_CHANGED"
    BROWSER_PROTECTION_TRIGGERED = "BROWSER_PROTECTION_TRIGGERED"
    BROWSER_DETECTED = "BROWSER_DETECTED"
    BROWSER_CLOSE_REQUESTED = "BROWSER_CLOSE_REQUESTED"
    BROWSER_CLOSE_SUCCEEDED = "BROWSER_CLOSE_SUCCEEDED"
    BROWSER_CLOSE_FAILED = "BROWSER_CLOSE_FAILED"
    SESSION_CLEANUP_STARTED = "SESSION_CLEANUP_STARTED"
    SESSION_CLEANUP_SUCCEEDED = "SESSION_CLEANUP_SUCCEEDED"
    SESSION_CLEANUP_FAILED = "SESSION_CLEANUP_FAILED"
    SESSION_CLEANUP_UNSUPPORTED = "SESSION_CLEANUP_UNSUPPORTED"


class BrowserProtectionMode(str, Enum):
    """Configuration modes for safe browser and session protection."""
    DISABLED = "DISABLED"
    CLOSE_BROWSER = "CLOSE_BROWSER"
    CLOSE_BROWSER_AND_CLEAR_SESSION_COOKIES = "CLOSE_BROWSER_AND_CLEAR_SESSION_COOKIES"


class LockReason(str, Enum):
    """Reason code triggering a workstation lock."""
    ABSENCE_TIMEOUT = "ABSENCE_TIMEOUT"
    UNKNOWN_FACE_TIMEOUT = "UNKNOWN_FACE_TIMEOUT"
    SPOOF_DETECTED = "SPOOF_DETECTED"
    MANUAL_LOCK = "MANUAL_LOCK"
    PIN_LOCKOUT = "PIN_LOCKOUT"
    CAMERA_DISCONNECTED = "CAMERA_DISCONNECTED"
    TAMPER_DETECTED = "TAMPER_DETECTED"


class LivenessTier(str, Enum):
    """Layers of anti-spoofing verification."""
    PASSIVE_TEXTURE = "PASSIVE_TEXTURE"
    EAR_BLINK = "EAR_BLINK"
    HEAD_POSE = "HEAD_POSE"
    CHALLENGE_RESPONSE = "CHALLENGE_RESPONSE"
